repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ['--diff', '--color']

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile', 'black']

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports']

  # Custom local hooks for Poetry
  - repo: local
    hooks:
      - id: poetry-lock
        name: Poetry Lock
        entry: poetry lock
        language: system
        types: [toml]
        files: ^pyproject\.toml$
        stages: [commit]
      
      - id: poetry-install
        name: Poetry Install
        entry: poetry install
        language: system
        types: [python, toml]
        stages: [commit]