repos:
  - repo: local
    hooks:
      - id: pre-commit-nox
        name: Pre-commit NoX Session
        entry: poetry run nox -s pre_commit
        language: system
        stages: [pre-commit]
        pass_filenames: false

      - id: poetry-lock
        name: Poetry Lock
        entry: poetry lock
        language: system
        types: [toml]
        files: ^pyproject\.toml$
        stages: [pre-commit]
        pass_filenames: false
       
      - id: poetry-install
        name: Poetry Install
        entry: poetry install
        language: system
        types: [python, toml]
        files: ^pyproject\.toml$|^poetry\.lock$
        stages: [pre-commit]
        pass_filenames: false
