name: Run Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
            - name: Setup Poetry
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                poetry install

            - name: Run tests
              run: |
                poetry run pytest

            - name: Lint code
              run: |
                poetry run flake8
                poetry run black --check .
                poetry run isort --check .

            - name: Type check
              run: |
                poetry run mypy .
